[package]
name = "id3-cli"
version = "0.0.0"
edition = "2021"
license = "MIT"

[lib]
name = "id3_cli"
path = "src/lib.rs"

[[bin]]
name = "id3"
path = "cli/id3.rs"

[dependencies]
id3 = "1.2.0"
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0.138", features = ["derive"] }
toml = "0.5.9"
serde_json = "1.0.82"
serde_yaml = "0.8.25"
thiserror = "1.0.31"
derive_more = "0.99.17"
pipe-trait = "0.4.0"
