[package]
name = "id3-cli"
version = "0.0.0"
edition = "2021"
license = "MIT"

[lib]
name = "id3_cli"
path = "src/lib.rs"

[[bin]]
name = "id3"
path = "cli/id3.rs"

[dependencies]
id3 = "1.2.0"
clap = { version = "3.1.18", features = ["derive"] }
pipe-trait = "0.4.0"
