name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache
        uses: actions/cache@v3
        timeout-minutes: 1
        continue-on-error: true
        if: matrix.os != 'macos-latest' # Cache seems to messing up macOS build
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-

      - uses: actions-rs/toolchain@v1.0.7
        with:
          components: rustfmt, clippy

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Use clippy to lint code
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test
