complete -c id3 -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c id3 -n "__fish_use_subcommand" -f -a "backup" -d 'Run backup without modification'
complete -c id3 -n "__fish_use_subcommand" -f -a "get" -d 'Show or export metadata'
complete -c id3 -n "__fish_use_subcommand" -f -a "set" -d 'Modify metadata'
complete -c id3 -n "__fish_use_subcommand" -f -a "delete" -d 'Delete metadata'
complete -c id3 -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c id3 -n "__fish_seen_subcommand_from backup" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "title" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "artist" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "album" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "album-artist" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "genre-name" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "genre-code" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "comment" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "picture" -d ''
complete -c id3 -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-name; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from title" -l format -d 'Format the output text into JSON or YAML' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from title" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from artist" -l format -d 'Format the output text into JSON or YAML' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from artist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from album" -l format -d 'Format the output text into JSON or YAML' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from album" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from album-artist" -l format -d 'Format the output text into JSON or YAML' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from album-artist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from genre-name" -l format -d 'Format the output text into JSON or YAML' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from genre-name" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from genre-code" -l format -d 'Format the output text into JSON or YAML' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from genre-code" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from comment" -l language -d 'Filter language' -r
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from comment" -l description -d 'Filter description' -r
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from comment" -l format -d 'Format of the output text. Required if there are multiple comments' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from comment" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from file; and not __fish_seen_subcommand_from dir; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from file; and not __fish_seen_subcommand_from dir; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List descriptions, mime types, picture types, and sizes of all pictures'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from file; and not __fish_seen_subcommand_from dir; and not __fish_seen_subcommand_from help" -f -a "file" -d 'Export a single picture to a file'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from file; and not __fish_seen_subcommand_from dir; and not __fish_seen_subcommand_from help" -f -a "dir" -d 'Export all single pictures to a directory'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from file; and not __fish_seen_subcommand_from dir; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from list" -l format -d 'Format of the output text' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from file" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from dir" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "title" -d ''
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "artist" -d ''
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "album" -d ''
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "album-artist" -d ''
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "genre-code" -d ''
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "comment" -d ''
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "picture" -d ''
complete -c id3 -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre-code; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from title" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from title" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from artist" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from artist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from album" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from album" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from album-artist" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from album-artist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from genre-code" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from genre-code" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from comment" -l language -d 'Comment language (ISO 639-2)' -r
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from comment" -l description -d 'Comment description' -r
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from comment" -l format -d 'Format of the ejected comment (if any)' -r -f -a "{json	,yaml	}"
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from comment" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from comment" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from picture" -l mime-type -d 'Mime type of the picture' -r
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from picture" -l description -d 'Description of the picture' -r
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from picture" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from picture" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "all" -d 'Remove the whole ID3 tag from the audio'
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "title" -d ''
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "artist" -d ''
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "album" -d ''
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "album-artist" -d ''
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "genre" -d ''
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "comment" -d ''
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "picture" -d ''
complete -c id3 -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from title; and not __fish_seen_subcommand_from artist; and not __fish_seen_subcommand_from album; and not __fish_seen_subcommand_from album-artist; and not __fish_seen_subcommand_from genre; and not __fish_seen_subcommand_from comment; and not __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from all" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from all" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from title" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from title" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from artist" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from artist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from album" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from album" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from album-artist" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from album-artist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from genre" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from genre" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from comment" -l description -d 'Comment description' -r
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from comment" -l content -d 'Comment content' -r
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from comment" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from comment" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -l no-backup -d 'Don\'t create backup for the target audio file'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "all" -d 'Delete all pictures'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Other"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Icon"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "OtherIcon"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "CoverFront"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "CoverBack"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Leaflet"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Media"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "LeadArtist"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Artist"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Conductor"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Band"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Composer"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Lyricist"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "RecordingLocation"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "DuringRecording"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "DuringPerformance"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "ScreenCapture"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "BrightFish"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "Illustration"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "BandLogo"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "PublisherLogo"
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from Other; and not __fish_seen_subcommand_from Icon; and not __fish_seen_subcommand_from OtherIcon; and not __fish_seen_subcommand_from CoverFront; and not __fish_seen_subcommand_from CoverBack; and not __fish_seen_subcommand_from Leaflet; and not __fish_seen_subcommand_from Media; and not __fish_seen_subcommand_from LeadArtist; and not __fish_seen_subcommand_from Artist; and not __fish_seen_subcommand_from Conductor; and not __fish_seen_subcommand_from Band; and not __fish_seen_subcommand_from Composer; and not __fish_seen_subcommand_from Lyricist; and not __fish_seen_subcommand_from RecordingLocation; and not __fish_seen_subcommand_from DuringRecording; and not __fish_seen_subcommand_from DuringPerformance; and not __fish_seen_subcommand_from ScreenCapture; and not __fish_seen_subcommand_from BrightFish; and not __fish_seen_subcommand_from Illustration; and not __fish_seen_subcommand_from BandLogo; and not __fish_seen_subcommand_from PublisherLogo; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from all" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Other" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Icon" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from OtherIcon" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from CoverFront" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from CoverBack" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Leaflet" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Media" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from LeadArtist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Artist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Conductor" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Band" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Composer" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Lyricist" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from RecordingLocation" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from DuringRecording" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from DuringPerformance" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from ScreenCapture" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from BrightFish" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from Illustration" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from BandLogo" -s h -l help -d 'Print help information'
complete -c id3 -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from picture; and __fish_seen_subcommand_from PublisherLogo" -s h -l help -d 'Print help information'
